#!/bin/sh
#
# Author: Pooya Moradi
# Date : 2022/04/11 | 1401-01-22
# License: MIT
#
# Description: A simple script to fetch Iranian and international calendar
#              events
#
# Dependencies: jq curl date jdate idate awk grep cut tr

# TODO

show_help() {
    cat << EOF
imroo: show Iranian/international calendar events for a date

Usage: imroo [OPTIONS] [DATE]
Arguments:
    [DATE]    Get events at given DATE (in Y/M/D format, Persian calendar)
              If empty, it is set to today
Options:
    -s        Sync database by downloading the json file from internet
    -d NUM    Number of days into future starting from DATE (including)
    -j        Use JSON as output format
    -V        Print script version
    -h        Display the help message

Examples:
    # sync before first use
    imroo -s
    # get events for current day
    imroo
    # get events for today, tomorrow, and the day after tomorrow
    imroo -d3
    # get events starting from 1404-11-10, and 5 days after it, in json
    imroo -j -d 6 "1404/11/10"
EOF
}

log() {
    _mode=""
    case "$1" in
        "error")
            _mode="error"
            ;;
        "warn")
            _mode="warn"
            ;;
        "info")
            _mode="info"
            ;;
        "debug")
            _mode="debug"
            ;;
    esac
    printf >&2 "[%-5s] %s\n" "$_mode" "$2"
}

check_deps() {
    _app=""
    _err=0
    for _app in "$@"; do
        if ! command -v "$_app" > /dev/null 2>&1; then
            log error "dependency $_app not found"
            _err=1
        fi
    done
    [ $_err -eq 1 ] && exit "$_err"
}

fetch() {
    _url="$1"
    _file="$2"
    if ! curl -# --fail --location "$_url" --output "$_file"; then
        return 1
    fi
}

sync() {
    log info "Syncing database to $data_dir"
    mkdir --parents "$data_dir"

    if ! fetch "$db_link" "$events"; then
        log error "Problem in downloading $db_link"
        return 1
    fi

    _db_files=$(printf '%s\n' "$data_dir/"*)
    log info "Downloaded files: $_db_files"
    log info "Done syncing"
}

get_month_day() {
    case "$1" in
        "Persian Calendar")
            jdate '+%m %d' --jalali \
                "$(date '+%Y/%m/%d' -d "$start_date + $offset days")"
            ;;
        "Hijri Calendar")
            idate --gregorian \
                  "$(date '+%Y%m%d' -d "$start_date + $offset days")" \
                | grep Output \
                | grep -o '[0-9]\+/[[:space:]]*[0-9]\+/[0-9]\+' \
                | awk -F/ '{print $2, $1}'
            ;;
        "Gregorian Calendar")
            date '+%m %d' -d "$start_date + $offset days"
            ;;
    esac
}

# deprecated
get_event() {
    _cal="$1"
    read -r month day << END
$(get_month_day "$_cal")
END

    if ! jq --raw-output \
        --arg cal "$_cal" \
        --argjson m "$month" --argjson d "$day" \
        '.[$cal] | map (select(.month == $m and .day == $d and
                              (.type == "Iran" or
                               .type == "International" or
                               .type == "AncientIran"))) []
                 as $m
                 | (if $m.holiday
                    then ($m.title + " (تعطیل)")
                    else $m.title end)' \
        "$events"; then
        log error "Filtering $events failed"
        exit 1
    fi
}

get_events() {
    # json array
    _keys="["
    for _cal in $calendars; do
        _cal="$_cal Calendar"
        if ! _result=$(get_month_day "$_cal"); then
            log error "Failed to get month/day for $_cal. Skipping..."
            continue
        fi
        read -r month day << EOF
        $_result
EOF

        # manually form the json element
        _key_json=$(
            cat << EOF
{"calendar": "$_cal", "month": $month, "day": $day}
EOF
        )
        _keys="$_keys$_key_json,"
    done
    # remove last comma
    _keys=$(printf '%s' "$_keys" | sed 's/,$//')
    _keys="$_keys]"

    # for -j mode, prepare a ISO (implying Gregorian) date
    iso_date=""
    if [ $out_json -eq 1 ]; then
        iso_date=$(date '+%Y-%m-%d' -d "$start_date + $offset days")
    fi

    if ! jq --raw-output \
        --argjson keys "$_keys" \
        --arg country "$country" \
        --argjson out_json "$out_json" \
        --arg iso_date "$iso_date" \
        'def get_event(cal; m; d):
             .[cal] | map (select(.month == m and .day == d and
                                 (.type == $country or
                                  .type == "International" or
                                  .type == "AncientIran"))) []
              as $event
              | if ($out_json == 1)
                then
                  $event + {"calendar" : cal} + {"iso_date": $iso_date}
                else
                  if $event.holiday
                  then ($event.title + " (تعطیل)")
                  else $event.title end
                end;
         . as $events
         | $keys[] as $key
         | $events | get_event($key.calendar; $key.month; $key.day)' \
        "$events"; then
        log error "Filtering $events failed"
        exit 1
    fi
}

# global variables
version=0.8
data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/imroo"
events="$data_dir/events.json"
db_link="https://github.com/persian-calendar/persian-calendar/raw/refs/heads/main/PersianCalendar/data/events.json"
days=1
offset=0
out_json=0
start_date=""
# desired calendars, mind the spaces and capitalizations
calendars="Persian Hijri Gregorian"
country="Iran"

while getopts sVhjd: opt; do
    case $opt in
        h)
            show_help
            exit
            ;;
        V)
            printf "%s\n" "$version"
            exit
            ;;
        s)
            sync
            exit "$?"
            ;;
        d)
            days="$OPTARG"
            ;;
        j)
            out_json=1
            ;;
        *)
            log error "Bad usage! Check help (-h)"
            exit 2
            ;;

    esac
done
shift "$((OPTIND - 1))"

if [ -n "$1" ]; then
    date_arg="$1"
    date_arg=$(printf "%s" "$date_arg" | tr '-' '/')
    start_date="$(jdate --gregorian="$date_arg")"
fi

check_deps jq curl jdate idate date

# check if db json file exists
if [ ! -f "$events" ]; then
    log error "Database not found. Sync first (-s)"
    exit 1
fi

# handle output json format
if [ $out_json -eq 1 ]; then
    e_json_stream=""
    while [ "$days" -gt 0 ]; do
        e_json_stream="$e_json_stream$(get_events)"
        days=$((days - 1))
        offset=$((offset + 1))
    done
    printf "%s" "$e_json_stream" | jq --slurp
    exit
fi

# handle output text format
if [ "$days" -eq 1 ]; then
    get_events
    exit
fi

while [ "$days" -gt 0 ]; do
    day_str=$(jdate '+%E' --jalali \
                    "$(date '+%Y/%m/%d' -d "$start_date + $offset days")" \
        | awk -F '،' '{print $1}')
    printf "«%s»\n" "$day_str"

    get_events

    days=$((days - 1))
    offset=$((offset + 1))
    printf "————————————————\n"
done
